# 0. Import Data

In [185]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
tf.config.run_functions_eagerly(True)

In [186]:
df = pd.read_csv('datacfd.csv')

In [187]:
df = df[["Strut wedge angle","Combustion chamber height","Top wall distance","Mach at outlet chamber","Shock angle","Slope after shock", "Slope chamber","Total Pressure","Total Temperature","Performace efficiency","Slope between shock and chamber"]]
X = pd.get_dummies(df.drop(["Strut wedge angle","Combustion chamber height","Top wall distance"], axis=1))
y = pd.get_dummies(df.drop(["Mach at outlet chamber","Shock angle","Slope after shock","Slope chamber","Total Pressure","Total Temperature","Performace efficiency","Slope between shock and chamber"], axis=1))

In [188]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)


# 1. Import Dependencies

In [191]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

# 2. Build and Compile Model

In [192]:
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=len(y_train.columns)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=8))

In [193]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])

# 3. Fit, Predict and Evaluate

In [196]:
X_test = np.asarray(X_test).astype(np.float16)
y_test = np.asarray(y_test).astype(np.float16)
X_train = np.asarray(X_train).astype(np.float16)
y_train = np.asarray(y_train).astype(np.float16)
model.fit(y_train, X_train, epochs=1500, batch_size=64)

Epoch 1/500
2/2 [==============================] - 0s 23ms/step - loss: 0.2241 - mean_squared_error: 0.2241
Epoch 2/500
2/2 [==============================] - 0s 17ms/step - loss: 0.2539 - mean_squared_error: 0.2539
Epoch 3/500
2/2 [==============================] - 0s 17ms/step - loss: 0.2553 - mean_squared_error: 0.2553
Epoch 4/500
2/2 [==============================] - 0s 18ms/step - loss: 0.2374 - mean_squared_error: 0.2374
Epoch 5/500
2/2 [==============================] - 0s 17ms/step - loss: 0.2453 - mean_squared_error: 0.2453
Epoch 6/500
2/2 [==============================] - 0s 17ms/step - loss: 0.2718 - mean_squared_error: 0.2718
Epoch 7/500
2/2 [==============================] - 0s 20ms/step - loss: 0.2450 - mean_squared_error: 0.2450
Epoch 8/500
2/2 [==============================] - 0s 17ms/step - loss: 0.2490 - mean_squared_error: 0.2490
Epoch 9/500
2/2 [==============================] - 0s 19ms/step - loss: 0.2501 - mean_squared_error: 0.2501
Epoch 10/500
2/2 [==========

In [197]:
y_hat = model.predict(y_test)

1/1 [==============================] - 0s 32ms/step


In [198]:
import matplotlib.pyplot as plt
import numpy as np


In [199]:
y_hat

array([[ 1.0847434 ,  0.7939759 , -1.1049173 ,  0.88094777,  1.040855  ,
         5.2866497 , -3.0690958 ,  0.8452792 ],
       [ 1.0685081 ,  0.7948007 , -1.9187248 ,  0.8786139 ,  1.0880696 ,
         5.1637573 , -2.8189545 ,  0.86236787],
       [ 1.0351697 ,  0.7611823 , -2.1436484 ,  0.98413914,  0.99021333,
         5.175737  , -2.6890118 ,  1.1123204 ],
       [ 1.0571207 ,  0.75040627, -2.1112106 ,  1.1121777 ,  0.97874796,
         4.883456  , -2.8176725 ,  0.78854036],
       [ 1.0928819 ,  0.716122  , -1.4398482 ,  0.9068622 ,  1.0221906 ,
         5.1276574 , -2.7812264 ,  0.8178638 ],
       [ 1.0302923 ,  0.51458573, -3.684633  ,  1.0413895 ,  0.991499  ,
         4.721375  , -1.6077199 ,  1.0947573 ],
       [ 1.0593753 ,  0.6977156 , -2.6052797 ,  0.8340411 ,  1.0948789 ,
         5.1472626 , -2.3121285 ,  1.0068233 ],
       [ 1.0240853 ,  0.7234449 , -2.621725  ,  1.1458352 ,  0.93051493,
         4.98011   , -2.5372944 ,  1.104543  ],
       [ 1.0508533 ,  0.76106524

In [213]:
S= np.array([[14.99,12.42,63.25]])

In [214]:
y_final=model.predict(S)

1/1 [==============================] - 0s 31ms/step


In [215]:
y_final[0]

array([ 1.0593317 ,  0.69764966, -2.605631  ,  0.8341164 ,  1.0948288 ,
        5.146965  , -2.3119504 ,  1.0067878 ], dtype=float32)

# 4. Saving and Reloading

In [226]:
import pickle

In [227]:
data = {"model": model}
with open('rom_num.pkl', 'wb') as file:
    pickle.dump(data, file)


INFO:tensorflow:Assets written to: ram://5fea3658-7f33-44e7-876a-a8c3cb51873c/assets


In [228]:
with open('rom_num.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]


In [230]:
y_pred = regressor_loaded.predict(S)
y_pred

1/1 [==============================] - 0s 36ms/step


array([[ 1.0593317 ,  0.69764966, -2.605631  ,  0.8341164 ,  1.0948288 ,
         5.146965  , -2.3119504 ,  1.0067878 ]], dtype=float32)